### ISSUE TITLE
error in stv function 

### ISSUE THREAD

**Issue by merliseclyde** [hanase/vote#9]
Thank you for a great package!
We were using the `stv` function to process ranks from a faculty search and encountered an unexpected error 

A reproducible example with the `ims_election` data is

```r
data(ims_election)
stv(ims_election[2:16,], nseats=8)
Error in !ic %in% group.members && nseats == group.nseats : 
  'length = 3' in coercion to 'logical(1)'
```

**Comment by merliseclyde** [comment]
This occurs in both the version on CRAN and 2.4.-1 on github.

**Comment by hanase** [comment]
Thanks for reporting this, @merliseclyde ! It should be fixed now.

**Comment by merliseclyde** [comment]
Great!   Works on my end as well now!
best,
Merlise

Merlise Clyde
Professor of Statistical Science and Director of Graduate Studies
Duke University

***@***.***?anonymous&ep=signature>             Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
